stages:
  - build
  - deploy

build-job:
  stage: build
  tags:
    - general
  rules:
    - if: $CI_COMMIT_TAG
  image: node:20-alpine
  script:
    - npm install
    - npm run build -- --configuration=production
    - echo "✅ Build done."
  artifacts:
    paths:
      - dist/billzy/browser/
    expire_in: 1 day

deploy-job:
  stage: deploy
  tags:
    - general
  rules:
    - if: $CI_COMMIT_TAG
      when: manual
  image: alpine:latest
  variables:
    VPS_USER: myinvoice
    VPS_IP: groupe12.glassworks-playground.fr
    TARGET_DIR: /var/www/myinvoice
  script:
    - chmod og= $SSH_PRIVATE_KEY
    - apk update && apk add openssh-client rsync
    - rsync -avz --delete -e "ssh -i $SSH_PRIVATE_KEY -o StrictHostKeyChecking=no" dist/billzy/browser/ $VPS_USER@$VPS_IP:$TARGET_DIR/
    - echo "✅ Deployment done."
